### ISSUE TITLE
python3 setup.py install

### ISSUE THREAD

**Issue by easycmdb** [BoyaaDataCenter/seed#2]
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'auther'
  warnings.warn(msg)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'auther_email'
  warnings.warn(msg)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running build
running build_assets
initializing git submodules
command failed [git submodule init] via [.]
Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    "Operating System :: OS Independent"
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 57, in run
    InstallCommand.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 46, in run
    self.run_command('build_assets')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/levi_yu/Documents/Dev/Python/seed/src/seed/utils/distutils/base.py", line 66, in run
    self._setup_git()
  File "/Users/levi_yu/Documents/Dev/Python/seed/src/seed/utils/distutils/base.py", line 29, in _setup_git
    self._run_command(['git', 'submodule', 'init'])
  File "/Users/levi_yu/Documents/Dev/Python/seed/src/seed/utils/distutils/base.py", line 57, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env, shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'submodule', 'init']' returned non-zero exit status 1.

**Comment by easycmdb** [comment]
安装的时候失败，但是执行git submodule init结果是正常的。 机器是mac

**Comment by sosofun123** [comment]
我也遇到这个问题

**Comment by ReoLei** [comment]
> 安装的时候失败，但是执行git submodule init结果是正常的。机器是mac


我并未复现出你说的这种情况.

也可以考虑使用pip install boyaa-seed 这种方式安装.
